In [1]:
import numpy as np

In [2]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
u,w,v = np.linalg.svd(A)
w = np.diag(w)
w = np.vstack([w, np.zeros((1, w.shape[1]))])
print("w", w)
w2 = np.where(np.abs(w) > 1e-6, 1, 0)

iw = 1/(w + 1e-10) * w2
print("w2", w2)

print("iw", iw)
pA  = v.T@iw@u.T
print(pA)

w [[9.508032   0.        ]
 [0.         0.77286964]
 [0.         0.        ]]
w2 [[1 0]
 [0 1]
 [0 0]]
iw [[0.10517424 0.        ]
 [0.         1.29387927]
 [0.         0.        ]]
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [4]:
pInv = np.linalg.pinv(A)
print(pInv)


[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
